### ISSUE TITLE
npm start doesn't work on v1.0.10

### ISSUE THREAD

**Issue by dbwodlf3** [anc95/ChatGPT-CodeReview#123]
version: v1.0.10

error flow
1.
npm i
2.
npm run start
3.
MODULE_NOT_FOUND
 Cannot find module 'gpt-reviewer/dist/index.js'

**Comment by anc95** [comment]
Thank you
